spring:
  application:
    name: microservie-consumer-movie-ribbon
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
#  instance:
#    prefer-ip-address: true